# -*- coding: utf-8 -*-
"""heart-disease-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIfhw3GHtv6g48k9Z-__6lR3zFMoxi-L

# Predicting heart disease using machine learning
This notebook looks into using various Python based machine learning and data science libraries in an attempt to build a machine learning model capable of predicting whether or not someone has heart disease based on their medical attributes.

Approach:
1. Problem Definition
2. Data
3. Evaluation
4. Features
5. Modelling
6. Experimentation

## 1. Problem Definition
Given clinical parameters about a patient, can we predic whether or not they have heart disease

## 2. Data
From Kaggle

## 3. Evaluation
If we reach 95% accuracy whether or not a patient has heart disease during the roof of concept, we'll go further.

## 4. Features
**Creating a data dictionary**

* age in years

* sex

* chest pain

* fasting blood sugar

## Data Dictionary
Feature	Description	Example Values
*
age	Age in years	29, 45, 60
sex	1 = male; 0 = female	0,
 * 1
cp	Chest pain type	0: Typical angina (chest pain), 1: Atypical angina (chest pain not related to heart), 2: Non-anginal pain (typically esophageal spasms (non heart related), 3: Asymptomatic (chest pain not showing signs of disea
s* e)
trestbps	Resting blood pressure (in mm Hg on admission to the hospital)	120, 140, 150
chol	Serum cholesterol in mg/dl	180, 220, 250
fbs	Fasting blood sugar > 120 mg/dl (1 = true; 0 = false)	0, 1
restecg	Resting electrocardiographic results	0: Nothing to note, 1: ST-T Wave abnormality, 2: Left ventricular hypertrophy
thalach	Maximum heart rate achieved	160, 180, 190
exang	Exercise induced angina (1 = yes; 0 = no)	0, 1
oldpeak	ST depression (heart potentially not getting enough oxygen) induced by exercise relative to rest	0.5, 1.0, 2.0
slope	The slope of the peak exercise ST segment	0: Upsloping, 1: Flatsloping, 2: Downsloping
ca	Number of major vessels (0-3) colored by fluoroscopy	0, 1, 2, 3
thal	Thalium stress result	1: Normal, 3: Normal, 6: Fixed defect, 7: Reversible defect
target	Have disease or not (1 = yes; 0 = no)	0, 1

## Preparing the tools

We're going to use pandas, matplotlib, and NUmpy for data analysis and manitpulation
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing tools that we need
# Regular EDA(exploratory data analysis) and plotting libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

# we want ut plots to appear inside the nitebook
# %matplotlib inline

# Models from Scikit_learn
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Model Evaluation
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import RocCurveDisplay

"""## Load Data"""

df = pd.read_csv("heart-disease.csv")
df
df.shape # This gives us the number of rows and columns(riws, columns)

"""## Data Exploration (EDA)
The goald is to find about the data, and become expert on the dataset we're working with.

1. What questions are we trying to solve?
2. What kind of data do we have and how do we treat differnt types?
3. What's missing from the data and hpw to deal with it?
4. What are the outliers and why should we care about it?
5. How can we add, change, or remove features to get more out of the data?
"""

df.head() # Gives us the top 5 rows and .tail gives the bottom 5

# Finding out how many each class are there for a particular column
df.target.value_counts() # Or df["target"].target_counts(), 1 means patient has the heart disease and 0 means they don't have it

df["target"].value_counts().plot(kind="bar", color=["red", "green"]);

df.info() #Gives us all the columns names and the number of values it has

# Checking if there is missing values
df.isna().sum()

df.describe() #This gives us the some stats about the data

"""### Heart Diseae Frequency according to Sex"""

df.sex.value_counts() #Male = 1 and Female = 2

# Comparing target column with sex column
pd.crosstab(df.target, df.sex)

# Creating a plot of crosstab
pd.crosstab(df.target, df.sex).plot(kind="bar", figsize=(10,6), color=["salmon", "lightblue"]);
#salmon is female and lightblue is male, and 0 in target is not having heart disease and 1 is having heart disease

plt.title("Heart Disease Frequency for Sex")
plt.xlabel("0 = No Disease, 1 = Heart Disease")
plt.ylabel("Number of Male and Females")
plt.legend(["Females", "Males"]);
plt.xticks(rotation=1) # 0 and 1 on the x axis

df.head()

"""### Age vs Max Heart rate(Thalach) for Heart Disease"""

# Creating another graph
plt.figure(figsize=(10,6))

#Scatter with positive examples
plt.scatter(df.age[df.target==1], df.thalach[df.target==1], color="green");

#Scatter with negative examples
plt.scatter(df.age[df.target==0], df.thalach[df.target==0], color="blue");

#Adding some helpful info
plt.title("Heart Disease in function of Age and Max Heart Rate")
plt.xlabel("Age")
plt.ylabel("Max Heart Rate")
plt.legend(["Disease", "No Disease"]);

# Checking the distribution of the age column with a histogram
df.age.plot.hist();

"""## Heart Disease Frequency per Chest Pain Type"""

pd.crosstab(df.cp, df.target)

# Crosstab Visuals
pd.crosstab(df.cp, df.target).plot(kind="bar", figsize=(10,6), color=["salmon", "lightblue"])

plt.title("Heart Disease Frequency Per Chest Pain Type")
plt.xlabel("Chest Pain Type")
plt.ylabel("Amount")
plt.legend(["No Disease", "Disease"])
plt.xticks(rotation=2);

# Making a correlation matrix
df.corr()

# Making our correlatin matrix a little visual

corr_matrix = df.corr()
fig, ax = plt.subplots(figsize=(15,10))
ax = sns.heatmap(corr_matrix, annot=True, linewidths=0.5, fmt = ".2f", cmap="YlGnBu");

# A higher value in the heat map means a positive correlation between the 2 attributes

"""## 5 Modelling"""

# Splitting the data into X and Y
X = df.drop("target", axis=1)
y = df["target"]
X

y

# Splitting data into train and test sets
np.random.seed(42)
#This will shuffle the data

# Splitting into train & test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train

"""Now that we have split our data into training and test sets, its time for the machine learning model.

We'll train it(find the patterns) on the trainig set.

And then we'll test(use the patterns) on the test set.

We're going to use 3 different machine learning models.
1. Logistic Regression
2. K-Nearest Neighbours Classifiers
3. Random Forest Classifiers
"""

# Putting models in the dictionary
models= {"Logistice Regression": LogisticRegression(),
         "KNN":KNeighborsClassifier(),
         "Random Forest": RandomForestClassifier()}

#Creating a function to fit and score models
def fit_and_score(models, X_train, X_test, y_train, y_test):
    """
    Fits and evaluates given a machine learning models.
    models: a dictionary of different Scikit-Learn Machine learning models.
    X_train: training data(no labels)
    X_test: testng data(no labels)
    y_train: training labels
    y_test: test_labels
    """

    # Set random seed
    np.random.seed(42)
    # Make a dictionary to model scores
    model_scores= {}
    # Loop through the models
    for name, model in models.items():
        # Fitting the model to the data
        model.fit(X_train, y_train)
        #Evauate the model and append the score to the model_scores
        model_scores[name] = model.score(X_test, y_test)

    return model_scores

model_scores = fit_and_score(models= models,
                             X_train =  X_train,
                             X_test = X_test,
                             y_train = y_train,
                             y_test = y_test)
model_scores

"""### Model Comparison"""

model_compare = pd.DataFrame(model_scores, index=["accuracy"])
model_compare.T.plot.bar();
# Using T makes them separate

"""Now we've got a baseline model... and we know a models first prediction aren't
always what we should based our next steps off.
    
Looking at the following
* Hyperparameter tuning (Same models, but changing some parameters)
* Feature importance
* Confusion matrix
* Cross-validation
* Precision
* Recall
* F1 Score
* Classification report
* ROC Curve
* Area under the curve (AUC)

### Hyperparameter Trainign
"""

# Tuning KNN

train_scores = []
test_scores = []

# Create s list of different values for n_neighbours
neighbors = range(1,21)

# Set up KNN Instance
knn = KNeighborsClassifier()

# Looping through different n_neighbors
for i in neighbors:
    knn.set_params(n_neighbors=i)


    # Fit the algorthim
    knn.fit(X_train, y_train)

    # Update the training scores list
    train_scores.append(knn.score(X_train, y_train))

    # Updating the test scores list
    test_scores.append(knn.score(X_test, y_test))

train_scores

plt.plot(neighbors, train_scores, label="Train Scores")
plt.plot(neighbors, test_scores, label="Test Scores")
plt.xticks(np.arange(1,21,1))
plt.xlabel("Number of neighbors")
plt.ylabel("Model Score")

plt.legend()

print(f"Maximum KNN score on the test data: {max(test_scores)*100: .2f}%")

"""## Hyperparamter tuning with RandomizedSearchCV(Cross Validation)

We're going to tune:
* Logistic Regression()
* RandomForestClassifier()
  
...using RandomizedSearchCV
"""

# Creating a hyperparamter grod for LogisticRegression
log_reg_grid = {"C" : np.logspace(-4,4,20),
                "solver":["liblinear"]}

# Creating a hyperparameter grid for RandomForestClassifier
rf_grid = {"n_estimators": np.arange(10,1000,50),
          "max_depth": [None, 3,5,10],
          "min_samples_split": np.arange(2,20,2),
          "min_samples_leaf": np.arange(1,20,2)}

"""Now we've got the hyperparameters grids setup for  each of the model, lets tune them using RandomizedSearchCV"""

# TUne LogisticRegression

np.random.seed(42)

# Setup random hyperparameter search fr logisticRegression'

rs_log_reg = RandomizedSearchCV(LogisticRegression(),
                                param_distributions=log_reg_grid,
                                cv=5,
                                n_iter=20,
                                verbose=True)
# 5 Times, and 20 iterations

# Fit random hyperparamter search model for logisitc Regression

rs_log_reg.fit(X_train, y_train)

rs_log_reg.best_params_

rs_log_reg.score(X_test, y_test)

"""We can now tune RandomForest"""

np.random.seed(42)

# Steup random hyperparameter searcg for RandomForestClassifier

rs_rf = RandomizedSearchCV(RandomForestClassifier(),
                                param_distributions=rf_grid,
                                cv=5,
                                n_iter=20,
                                verbose=True)
# Fit random hyperparameter searchmodel for RandomForestClassifier()
rs_rf.fit(X_train, y_train)

# Finding the bets hyperparameters
rs_rf.best_params_

# Evaluating the randomized search RandomForetClassifier
rs_rf.score(X_test, y_test)

"""## HyperParameter Tuning with GridSearchCV

Since our LogisticRegression model provides us the best socre so far, we'll try to improve them aginst GridSearchCV
"""

# Different hyperparameter for LogisiticRegression model
log_reg_grid = {"C": np.logspace(-4,4,30),
                "solver": ["liblinear"]}

# Setting up hyperparameter seragc for LogisiticRegression
gs_log_reg = GridSearchCV(LogisticRegression(),
                          param_grid=log_reg_grid,
                          cv=5,
                          verbose=True)

# Fit grid hyperparameter serach model
gs_log_reg.fit(X_train, y_train)

# Checking the best hyperparameter

gs_log_reg.best_params_

# Evaluate the grid search Logistic Regression mdel
gs_log_reg.score(X_test, y_test)

"""## Evaluating the tuned machine learning classifier, beyond accuracy

* ROC Curve and AUC score
* Confusion matrix
* Classification report
* Precision
* Recall
* F1-score
  
and it would be great if cross-validation was used where possible.

To make comparisons and evaluate our trained model first we need to make predictions
"""

# Make predictions with tuned model

y_preds = gs_log_reg.predict(X_test)

"""y_preds"""

y_test

# ROC curve is created by plotting the true positive rate against the false positive rate at various threshold settings
# Plotting ROC curve and calculate the AUC matrix
RocCurveDisplay.from_estimator(estimator=gs_log_reg,
                               X=X_test,
                               y=y_test);

print(confusion_matrix(y_test, y_preds))

sns.set(font_scale=1.5)

def plot_conf_mat(y_test, y_preds):
    """
    Plots confusion matrix using seaborn's heatmap()
    """

fig, ax= plt.subplots(figsize=(3,3))
ax = sns.heatmap(confusion_matrix(y_test, y_preds),
                 annot=True,
                 cbar=False)
plt.xlabel("True Label")
plt.ylabel("Predicted Label")

plot_conf_mat(y_test, y_preds)

"""We have a ROC Curve and AUC metric and Confusion matrix, now we'll get the classification report and cross-validated precision"""

print(classification_report(y_test, y_preds))

"""## Calculating evaluation metrics using cross-validation

We're going to calculate the precision, and f1-score of the model using corss-valiadtion and to do so we'll be using cross_val_score()
"""

# Checking the best hyperparameter

gs_log_reg.best_params_

# Creating anew classifier with the best parameters
clf = LogisticRegression(C=0.20433597178569418,
                        solver="liblinear")

# Cross-validated accuracy
cv_acc = cross_val_score(clf,
                         X,
                         y,
                         cv=5,
                         scoring="accuracy")
cv_acc

cv_acc = np.mean(cv_acc)
cv_acc

# Cross-validated precision
cv_precision = cross_val_score(clf,
                         X,
                         y,
                         cv=5,
                         scoring="precision")
cv_precision = np.mean(cv_precision)
cv_precision

# Cross-validated recall
cv_recall = cross_val_score(clf,
                         X,
                         y,
                         cv=5,
                         scoring="recall")
cv_recall = np.mean(cv_recall)
cv_recall

# Cross-validated f1-score
cv_f1 = cross_val_score(clf,
                         X,
                         y,
                         cv=5,
                         scoring="f1")
cv_f1 = np.mean(cv_f1)
cv_f1

# Visualize corss-validated metrics
cv_metrics = pd.DataFrame({"Accuracy": cv_acc,
                           "Precision":cv_precision,
                           "Recall": cv_recall,
                           "F1": cv_f1},
                          index=[0])

cv_metrics.T.plot.bar(title="Cross-validated classification metrics", legend=False)

"""### Feature Importance

Feature Importance is which features contributed most to the outcomes of the model and how did they contribute?

It is different for eahc machine learning model. One way to find is to find the feature importance is to search the model name + feature importance.
Here we're going to find the feature importance for LogisticRregression
"""

# Fitting an instance of LogisticRegrssion

gs_log_reg.best_params_

clf = LogisticRegression(C=0.20433597178569418,
                         solver="liblinear")

clf.fit(X_train, y_train)

# Checking coefficient
clf.coef_

# Matching the coef of featues of columns
feature_dict=dict(zip(df.columns, list(clf.coef_[0])))
feature_dict
#How much each atttribute affects the target

# Visualize feature importance

feature_df = pd.DataFrame(feature_dict, index=[0])
feature_df.T.plot.bar(title="Feature Importance", legend=False)

pd.crosstab(df["sex"],df["target"])

pd.crosstab(df["slope"], df["target"])

"""### Experimentation

If we still haven't reached our evluation metric then..
* Should we collect more data?
* Try a different model?
* Improve the current model?
  
"""